services:
  db:
    container_name: postgres_container
    image: postgres:14.18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mochache_demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: brian56
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  airflow:
    container_name: airflow_container
    image: apache/airflow:3.0.3
    
    ports:
      - "8080:8080"
    environment:
      AIRFLOW_DATABASE_SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:brian56@db:5432/mochache_demo
  
    volumes:
        - ./dags:/opt/airflow/dags
        - ./postgres/airflow_init.sql:/docker-entrypoint-initdb.d/airflow_init.sql
        
    depends_on:
      - db

    command: airflow standalone
    networks:
      - my_network
    
  dbt:
    container_name: dbt_container
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.0
    volumes:
      - ./weather-data-project:/usr/app
    

    working_dir: /usr/app
    depends_on:
      - db
    networks:
      - my_network
    command: init my_project

networks:
  my_network:
    driver: bridge
